<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Email_Copy_Setting {
    private $ctfbcc_options;

    public function ctfbcc_add_plugin_page() {
        add_options_page(
            '询盘抄送', // page_title
            '询盘抄送', // menu_title
            'manage_options', // capability
            'ctfbcc', // menu_slug
            array( $this, 'ctfbcc_create_admin_page' ) // function
        );
    }

    public function ctfbcc_create_admin_page() {
        $this->ctfbcc_options = get_option( 'ctfbcc_option_name' ); ?>

        <div class="wrap">
            <h2>询盘抄送</h2>
            <p>可以隐藏某字段再抄送</p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields( 'ctfbcc_option_group' );
                do_settings_sections( 'ctfbcc-admin' );
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function ctfbcc_page_init() {
        register_setting(
            'ctfbcc_option_group', // option_group
            'ctfbcc_option_name', // option_name
            array( $this, 'ctfbcc_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'ctfbcc_setting_section', // id
            'Settings', // title
            array( $this, 'ctfbcc_section_info' ), // callback
            'ctfbcc-admin' // page
        );

        add_settings_field(
            'emails_0', // id
            'Emails', // title
            array( $this, 'emails_0_callback' ), // callback
            'ctfbcc-admin', // page
            'ctfbcc_setting_section' // section
        );

        add_settings_field(
            'fields_1', // id
            'Fields', // title
            array( $this, 'fields_1_callback' ), // callback
            'ctfbcc-admin', // page
            'ctfbcc_setting_section' // section
        );
    }

    public function ctfbcc_sanitize($input) {
        $sanitary_values = array();
        if ( isset( $input['emails_0'] ) ) {
            $sanitary_values['emails_0'] = sanitize_text_field( $input['emails_0'] );
        }

        if ( isset( $input['fields_1'] ) ) {
            $sanitary_values['fields_1'] = sanitize_text_field( $input['fields_1'] );
        }

        return $sanitary_values;
    }

    public function ctfbcc_section_info() {

    }

    public function emails_0_callback() {
        printf(
            '<input class="regular-text" type="text" name="ctfbcc_option_name[emails_0]" id="emails_0" value="%s">',
            isset( $this->ctfbcc_options['emails_0'] ) ? esc_attr( $this->ctfbcc_options['emails_0']) : ''
        );
    }

    public function fields_1_callback() {
        printf(
            '<input class="regular-text" type="text" name="ctfbcc_option_name[fields_1]" id="fields_1" value="%s">',
            isset( $this->ctfbcc_options['fields_1'] ) ? esc_attr( $this->ctfbcc_options['fields_1']) : ''
        );
    }

}